// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fsvjoabunvedifukozxk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzdmpvYWJ1bnZlZGlmdWtvenhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYzMzk4MTIsImV4cCI6MjA1MTkxNTgxMn0.Topvn0Hb5FqB2kFndUgjV1zlpkXneCpfizyQxHSU-gc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);